import SVGIcon from './SVGIcon';

import AlarmOn from './AlarmOn';
import AlarmOff from './AlarmOff';
import Close from './Close';
import Dribbble from './Dribbble';
import Github from './Github';
import Email from './Email';
import NoteSolid from './NoteSolid';
import NoteOutline from './NoteOutline';
import EventChecked from './EventChecked';
import EventDisabled from './EventDisabled';
import EventUnchecked from './EventUnchecked';
import KeyDown from './KeyDown';
import Person from './Person';
import Search from './Search';
import Schedule from './Schedule';
import TaskChecked from './TaskChecked';
import TaskDisabled from './TaskDisabled';
import TaskUnchecked from './TaskUnchecked';
import Twitter from './Twitter';

SVGIcon.AlarmOn = AlarmOn;
SVGIcon.AlarmOff = AlarmOff;
SVGIcon.Close = Close;
SVGIcon.Dribbble = Dribbble;
SVGIcon.Github = Github;
SVGIcon.Email = Email;
SVGIcon.NoteSolid = NoteSolid;
SVGIcon.NoteOutline = NoteOutline;
SVGIcon.EventChecked = EventChecked;
SVGIcon.EventDisabled = EventDisabled;
SVGIcon.EventUnchecked = EventUnchecked;
SVGIcon.KeyDown = KeyDown;
SVGIcon.Person = Person;
SVGIcon.Search = Search;
SVGIcon.Schedule = Schedule;
SVGIcon.TaskChecked = TaskChecked;
SVGIcon.TaskDisabled = TaskDisabled;
SVGIcon.TaskUnchecked = TaskUnchecked;
SVGIcon.Twitter = Twitter;

export default SVGIcon;
